// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fleet-monitor.proto

package fleet_monitor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_monitor_f578b9334782262b, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AvailableVehiclesResponse struct {
	Vehicles             []*AvailableVehiclesResponse_Vehicle `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *AvailableVehiclesResponse) Reset()         { *m = AvailableVehiclesResponse{} }
func (m *AvailableVehiclesResponse) String() string { return proto.CompactTextString(m) }
func (*AvailableVehiclesResponse) ProtoMessage()    {}
func (*AvailableVehiclesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_monitor_f578b9334782262b, []int{1}
}
func (m *AvailableVehiclesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableVehiclesResponse.Unmarshal(m, b)
}
func (m *AvailableVehiclesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableVehiclesResponse.Marshal(b, m, deterministic)
}
func (dst *AvailableVehiclesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableVehiclesResponse.Merge(dst, src)
}
func (m *AvailableVehiclesResponse) XXX_Size() int {
	return xxx_messageInfo_AvailableVehiclesResponse.Size(m)
}
func (m *AvailableVehiclesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableVehiclesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableVehiclesResponse proto.InternalMessageInfo

func (m *AvailableVehiclesResponse) GetVehicles() []*AvailableVehiclesResponse_Vehicle {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

type AvailableVehiclesResponse_Vehicle struct {
	VehicleId              string   `protobuf:"bytes,1,opt,name=VehicleId,proto3" json:"VehicleId,omitempty"`
	Location               string   `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	ApproximateRadialRange uint32   `protobuf:"varint,3,opt,name=ApproximateRadialRange,proto3" json:"ApproximateRadialRange,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *AvailableVehiclesResponse_Vehicle) Reset()         { *m = AvailableVehiclesResponse_Vehicle{} }
func (m *AvailableVehiclesResponse_Vehicle) String() string { return proto.CompactTextString(m) }
func (*AvailableVehiclesResponse_Vehicle) ProtoMessage()    {}
func (*AvailableVehiclesResponse_Vehicle) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_monitor_f578b9334782262b, []int{1, 0}
}
func (m *AvailableVehiclesResponse_Vehicle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableVehiclesResponse_Vehicle.Unmarshal(m, b)
}
func (m *AvailableVehiclesResponse_Vehicle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableVehiclesResponse_Vehicle.Marshal(b, m, deterministic)
}
func (dst *AvailableVehiclesResponse_Vehicle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableVehiclesResponse_Vehicle.Merge(dst, src)
}
func (m *AvailableVehiclesResponse_Vehicle) XXX_Size() int {
	return xxx_messageInfo_AvailableVehiclesResponse_Vehicle.Size(m)
}
func (m *AvailableVehiclesResponse_Vehicle) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableVehiclesResponse_Vehicle.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableVehiclesResponse_Vehicle proto.InternalMessageInfo

func (m *AvailableVehiclesResponse_Vehicle) GetVehicleId() string {
	if m != nil {
		return m.VehicleId
	}
	return ""
}

func (m *AvailableVehiclesResponse_Vehicle) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *AvailableVehiclesResponse_Vehicle) GetApproximateRadialRange() uint32 {
	if m != nil {
		return m.ApproximateRadialRange
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*AvailableVehiclesResponse)(nil), "AvailableVehiclesResponse")
	proto.RegisterType((*AvailableVehiclesResponse_Vehicle)(nil), "AvailableVehiclesResponse.Vehicle")
}

func init() { proto.RegisterFile("fleet-monitor.proto", fileDescriptor_fleet_monitor_f578b9334782262b) }

var fileDescriptor_fleet_monitor_f578b9334782262b = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xcb, 0x49, 0x4d,
	0x2d, 0xd1, 0xcd, 0xcd, 0xcf, 0xcb, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57,
	0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x54, 0xba, 0xc1, 0xc8, 0x25, 0xe9, 0x58, 0x96,
	0x98, 0x99, 0x93, 0x98, 0x94, 0x93, 0x1a, 0x96, 0x9a, 0x91, 0x99, 0x9c, 0x93, 0x5a, 0x1c, 0x94,
	0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xc7, 0xc5, 0x51, 0x06, 0x15, 0x93, 0x60, 0x54,
	0x60, 0xd6, 0xe0, 0x36, 0x52, 0xd2, 0xc3, 0xa9, 0x5a, 0x0f, 0x2a, 0x10, 0x04, 0xd7, 0x23, 0x55,
	0xcd, 0xc5, 0x0e, 0x15, 0x14, 0x92, 0xe1, 0xe2, 0x84, 0x32, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x52, 0x5c, 0x1c, 0x3e, 0xf9, 0xc9, 0x89, 0x25, 0x99, 0xf9,
	0x79, 0x12, 0x4c, 0x60, 0x49, 0x38, 0x5f, 0xc8, 0x8c, 0x4b, 0xcc, 0xb1, 0xa0, 0xa0, 0x28, 0xbf,
	0x22, 0x33, 0x37, 0xb1, 0x24, 0x35, 0x28, 0x31, 0x25, 0x33, 0x31, 0x27, 0x28, 0x31, 0x2f, 0x3d,
	0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x37, 0x08, 0x87, 0xac, 0x91, 0x27, 0x17, 0x8f, 0x1b, 0xc8,
	0xeb, 0xbe, 0x10, 0x9f, 0x0b, 0x59, 0x72, 0x09, 0x62, 0xb8, 0x5d, 0x88, 0x4d, 0x0f, 0x1c, 0x0e,
	0x52, 0x52, 0xb8, 0xfd, 0xa5, 0xc4, 0x90, 0xc4, 0x06, 0x0e, 0x35, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0a, 0x8b, 0x7f, 0xbf, 0x4c, 0x01, 0x00, 0x00,
}
