// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-management.proto

package user_management

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	LicenseId            string   `protobuf:"bytes,5,opt,name=LicenseId,proto3" json:"LicenseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_a9d3317c816f6e19, []int{0}
}
func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(dst, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterUserRequest) GetLicenseId() string {
	if m != nil {
		return m.LicenseId
	}
	return ""
}

type RegisterUserResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_a9d3317c816f6e19, []int{1}
}
func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(dst, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *RegisterUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IssueUserTokenRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueUserTokenRequest) Reset()         { *m = IssueUserTokenRequest{} }
func (m *IssueUserTokenRequest) String() string { return proto.CompactTextString(m) }
func (*IssueUserTokenRequest) ProtoMessage()    {}
func (*IssueUserTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_a9d3317c816f6e19, []int{2}
}
func (m *IssueUserTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueUserTokenRequest.Unmarshal(m, b)
}
func (m *IssueUserTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueUserTokenRequest.Marshal(b, m, deterministic)
}
func (dst *IssueUserTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueUserTokenRequest.Merge(dst, src)
}
func (m *IssueUserTokenRequest) XXX_Size() int {
	return xxx_messageInfo_IssueUserTokenRequest.Size(m)
}
func (m *IssueUserTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueUserTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssueUserTokenRequest proto.InternalMessageInfo

func (m *IssueUserTokenRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *IssueUserTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type IssueUserTokenResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueUserTokenResponse) Reset()         { *m = IssueUserTokenResponse{} }
func (m *IssueUserTokenResponse) String() string { return proto.CompactTextString(m) }
func (*IssueUserTokenResponse) ProtoMessage()    {}
func (*IssueUserTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_a9d3317c816f6e19, []int{3}
}
func (m *IssueUserTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueUserTokenResponse.Unmarshal(m, b)
}
func (m *IssueUserTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueUserTokenResponse.Marshal(b, m, deterministic)
}
func (dst *IssueUserTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueUserTokenResponse.Merge(dst, src)
}
func (m *IssueUserTokenResponse) XXX_Size() int {
	return xxx_messageInfo_IssueUserTokenResponse.Size(m)
}
func (m *IssueUserTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueUserTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IssueUserTokenResponse proto.InternalMessageInfo

func (m *IssueUserTokenResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *IssueUserTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserRequest) Reset()         { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()    {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_a9d3317c816f6e19, []int{4}
}
func (m *AuthenticateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserRequest.Unmarshal(m, b)
}
func (m *AuthenticateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserRequest.Merge(dst, src)
}
func (m *AuthenticateUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserRequest.Size(m)
}
func (m *AuthenticateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserRequest proto.InternalMessageInfo

func (m *AuthenticateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateUserResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=Authenticated,proto3" json:"Authenticated,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserResponse) Reset()         { *m = AuthenticateUserResponse{} }
func (m *AuthenticateUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserResponse) ProtoMessage()    {}
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_a9d3317c816f6e19, []int{5}
}
func (m *AuthenticateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserResponse.Unmarshal(m, b)
}
func (m *AuthenticateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserResponse.Merge(dst, src)
}
func (m *AuthenticateUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserResponse.Size(m)
}
func (m *AuthenticateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserResponse proto.InternalMessageInfo

func (m *AuthenticateUserResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *AuthenticateUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthenticateUserResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "RegisterUserResponse")
	proto.RegisterType((*IssueUserTokenRequest)(nil), "IssueUserTokenRequest")
	proto.RegisterType((*IssueUserTokenResponse)(nil), "IssueUserTokenResponse")
	proto.RegisterType((*AuthenticateUserRequest)(nil), "AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateUserResponse)(nil), "AuthenticateUserResponse")
}

func init() {
	proto.RegisterFile("user-management.proto", fileDescriptor_user_management_a9d3317c816f6e19)
}

var fileDescriptor_user_management_a9d3317c816f6e19 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x6d, 0xfa, 0xb5, 0xa5, 0xbd, 0x7c, 0x16, 0x19, 0xfb, 0x13, 0x83, 0x88, 0x0c, 0x2e, 0xdc,
	0x38, 0x82, 0xae, 0x5d, 0x88, 0x28, 0x04, 0x6b, 0x91, 0xa8, 0x0f, 0x30, 0x26, 0xd7, 0x1a, 0x6c,
	0x92, 0x9a, 0x3b, 0xc1, 0xc7, 0xf1, 0xd1, 0x7c, 0x15, 0x49, 0x66, 0x5a, 0x93, 0x9a, 0xba, 0x71,
	0x97, 0x7b, 0x2e, 0x67, 0x38, 0x3f, 0x37, 0x30, 0xcc, 0x08, 0xd3, 0xe3, 0x48, 0xc6, 0x72, 0x86,
	0x11, 0xc6, 0x4a, 0x2c, 0xd2, 0x44, 0x25, 0xfc, 0xc3, 0x82, 0x1d, 0x0f, 0x67, 0x21, 0x29, 0x4c,
	0x1f, 0x09, 0x53, 0x0f, 0xdf, 0x32, 0x24, 0xc5, 0x06, 0xd0, 0xbe, 0x8a, 0x64, 0x38, 0xb7, 0xad,
	0x03, 0xeb, 0xa8, 0xe7, 0xe9, 0x81, 0x39, 0xd0, 0xbd, 0x93, 0x44, 0xef, 0x49, 0x1a, 0xd8, 0xcd,
	0x62, 0xb1, 0x9a, 0xd9, 0x1e, 0xf4, 0xae, 0xc3, 0x94, 0xd4, 0x54, 0x46, 0x68, 0xff, 0x2b, 0x96,
	0xdf, 0x40, 0xce, 0x9c, 0x48, 0xb3, 0x6c, 0x69, 0xe6, 0x72, 0xce, 0x99, 0x93, 0xd0, 0xc7, 0x98,
	0xd0, 0x0d, 0xec, 0xb6, 0x66, 0xae, 0x00, 0x3e, 0x81, 0x41, 0x55, 0x20, 0x2d, 0x92, 0x98, 0x90,
	0xed, 0x03, 0xdc, 0x67, 0xbe, 0x8f, 0x44, 0xcf, 0x99, 0x96, 0xd9, 0xf5, 0x4a, 0x48, 0xee, 0xe0,
	0x21, 0x79, 0xc5, 0xd8, 0x08, 0xd5, 0x03, 0xbf, 0x81, 0xa1, 0x4b, 0x94, 0x61, 0xfe, 0x54, 0x81,
	0x2c, 0x0d, 0x8f, 0xa0, 0x93, 0x63, 0x6e, 0x60, 0x1c, 0x9b, 0xe9, 0x37, 0xcb, 0x7c, 0x0a, 0xa3,
	0xf5, 0xc7, 0xfe, 0x24, 0xee, 0x04, 0xc6, 0x17, 0x99, 0x7a, 0xc1, 0x58, 0x85, 0xbe, 0x54, 0xb8,
	0xd6, 0x87, 0x26, 0x58, 0x65, 0xc2, 0x1c, 0xec, 0x9f, 0x04, 0x23, 0xe1, 0x10, 0xb6, 0xca, 0xbb,
	0xc0, 0xa8, 0xa8, 0x82, 0x25, 0xdb, 0xcd, 0x8a, 0x6d, 0x06, 0x2d, 0x2f, 0x99, 0x2f, 0x8b, 0x2c,
	0xbe, 0x4f, 0x3f, 0x2d, 0xe8, 0xe7, 0xeb, 0xdb, 0xd5, 0x11, 0xb1, 0x73, 0xf8, 0x5f, 0x2e, 0x87,
	0x0d, 0x44, 0xcd, 0x31, 0x39, 0x43, 0x51, 0xd7, 0x20, 0x6f, 0xb0, 0x4b, 0xe8, 0x57, 0x03, 0x64,
	0x23, 0x51, 0x5b, 0x8f, 0x33, 0x16, 0xf5, 0x49, 0xf3, 0x06, 0x73, 0x61, 0x7b, 0x3d, 0x04, 0x66,
	0x8b, 0x0d, 0x41, 0x3a, 0xbb, 0x62, 0x53, 0x62, 0xbc, 0xf1, 0xd4, 0x29, 0x7e, 0x8a, 0xb3, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x76, 0x93, 0xf3, 0x2d, 0x03, 0x00, 0x00,
}
