// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-management.proto

package user_management

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticateUserRequest struct {
	JWT                  string   `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserRequest) Reset()         { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()    {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_53617772469dc3cb, []int{0}
}
func (m *AuthenticateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserRequest.Unmarshal(m, b)
}
func (m *AuthenticateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserRequest.Merge(dst, src)
}
func (m *AuthenticateUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserRequest.Size(m)
}
func (m *AuthenticateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserRequest proto.InternalMessageInfo

func (m *AuthenticateUserRequest) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

type AuthenticateUserResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=Authenticated,proto3" json:"Authenticated,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserResponse) Reset()         { *m = AuthenticateUserResponse{} }
func (m *AuthenticateUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserResponse) ProtoMessage()    {}
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_53617772469dc3cb, []int{1}
}
func (m *AuthenticateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserResponse.Unmarshal(m, b)
}
func (m *AuthenticateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserResponse.Merge(dst, src)
}
func (m *AuthenticateUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserResponse.Size(m)
}
func (m *AuthenticateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserResponse proto.InternalMessageInfo

func (m *AuthenticateUserResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *AuthenticateUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthenticateUserResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateUserRequest)(nil), "AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateUserResponse)(nil), "AuthenticateUserResponse")
}

func init() {
	proto.RegisterFile("user-management.proto", fileDescriptor_user_management_53617772469dc3cb)
}

var fileDescriptor_user_management_53617772469dc3cb = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2d, 0x4e, 0x2d,
	0xd2, 0xcd, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x57, 0xd2, 0xe6, 0x12, 0x77, 0x2c, 0x2d, 0xc9, 0x48, 0xcd, 0x2b, 0xc9, 0x4c, 0x4e, 0x2c,
	0x49, 0x0d, 0x2d, 0x4e, 0x2d, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62,
	0xf6, 0x0a, 0x0f, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x72, 0xb8, 0x24,
	0x30, 0x15, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xa9, 0x70, 0xf1, 0x22, 0xcb, 0xa5, 0x80,
	0xf5, 0x71, 0x04, 0xa1, 0x0a, 0x0a, 0x89, 0x71, 0xb1, 0x81, 0x74, 0x79, 0xa6, 0x48, 0x30, 0x81,
	0x8d, 0x85, 0xf2, 0x84, 0x84, 0xb8, 0x58, 0x82, 0xf2, 0x73, 0x52, 0x25, 0x98, 0xc1, 0xa2, 0x60,
	0xb6, 0x51, 0x34, 0x17, 0x1f, 0x48, 0xd6, 0x17, 0xee, 0x64, 0x21, 0x4f, 0x2e, 0x01, 0x74, 0xfb,
	0x85, 0x24, 0xf4, 0x70, 0xb8, 0x5f, 0x4a, 0x52, 0x0f, 0x97, 0x63, 0x95, 0x18, 0x92, 0xd8, 0xc0,
	0xde, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x77, 0x76, 0x74, 0x17, 0x01, 0x00, 0x00,
}
