// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-management.proto

package user_management

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterCustomerRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	LicenseId            string   `protobuf:"bytes,5,opt,name=LicenseId,proto3" json:"LicenseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerRequest) Reset()         { *m = RegisterCustomerRequest{} }
func (m *RegisterCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerRequest) ProtoMessage()    {}
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_2f3ba80db759a4f0, []int{0}
}
func (m *RegisterCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerRequest.Unmarshal(m, b)
}
func (m *RegisterCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerRequest.Merge(dst, src)
}
func (m *RegisterCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerRequest.Size(m)
}
func (m *RegisterCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerRequest proto.InternalMessageInfo

func (m *RegisterCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterCustomerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterCustomerRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterCustomerRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterCustomerRequest) GetLicenseId() string {
	if m != nil {
		return m.LicenseId
	}
	return ""
}

type RegisterCustomerResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerResponse) Reset()         { *m = RegisterCustomerResponse{} }
func (m *RegisterCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerResponse) ProtoMessage()    {}
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_2f3ba80db759a4f0, []int{1}
}
func (m *RegisterCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerResponse.Unmarshal(m, b)
}
func (m *RegisterCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerResponse.Merge(dst, src)
}
func (m *RegisterCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerResponse.Size(m)
}
func (m *RegisterCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerResponse proto.InternalMessageInfo

func (m *RegisterCustomerResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *RegisterCustomerResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IssueUserTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueUserTokenRequest) Reset()         { *m = IssueUserTokenRequest{} }
func (m *IssueUserTokenRequest) String() string { return proto.CompactTextString(m) }
func (*IssueUserTokenRequest) ProtoMessage()    {}
func (*IssueUserTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_2f3ba80db759a4f0, []int{2}
}
func (m *IssueUserTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueUserTokenRequest.Unmarshal(m, b)
}
func (m *IssueUserTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueUserTokenRequest.Marshal(b, m, deterministic)
}
func (dst *IssueUserTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueUserTokenRequest.Merge(dst, src)
}
func (m *IssueUserTokenRequest) XXX_Size() int {
	return xxx_messageInfo_IssueUserTokenRequest.Size(m)
}
func (m *IssueUserTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueUserTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssueUserTokenRequest proto.InternalMessageInfo

func (m *IssueUserTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *IssueUserTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type IssueUserTokenResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueUserTokenResponse) Reset()         { *m = IssueUserTokenResponse{} }
func (m *IssueUserTokenResponse) String() string { return proto.CompactTextString(m) }
func (*IssueUserTokenResponse) ProtoMessage()    {}
func (*IssueUserTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_2f3ba80db759a4f0, []int{3}
}
func (m *IssueUserTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueUserTokenResponse.Unmarshal(m, b)
}
func (m *IssueUserTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueUserTokenResponse.Marshal(b, m, deterministic)
}
func (dst *IssueUserTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueUserTokenResponse.Merge(dst, src)
}
func (m *IssueUserTokenResponse) XXX_Size() int {
	return xxx_messageInfo_IssueUserTokenResponse.Size(m)
}
func (m *IssueUserTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueUserTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IssueUserTokenResponse proto.InternalMessageInfo

func (m *IssueUserTokenResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *IssueUserTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserRequest) Reset()         { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()    {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_2f3ba80db759a4f0, []int{4}
}
func (m *AuthenticateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserRequest.Unmarshal(m, b)
}
func (m *AuthenticateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserRequest.Merge(dst, src)
}
func (m *AuthenticateUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserRequest.Size(m)
}
func (m *AuthenticateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserRequest proto.InternalMessageInfo

func (m *AuthenticateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateUserResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=Authenticated,proto3" json:"Authenticated,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserResponse) Reset()         { *m = AuthenticateUserResponse{} }
func (m *AuthenticateUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserResponse) ProtoMessage()    {}
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_management_2f3ba80db759a4f0, []int{5}
}
func (m *AuthenticateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserResponse.Unmarshal(m, b)
}
func (m *AuthenticateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserResponse.Merge(dst, src)
}
func (m *AuthenticateUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserResponse.Size(m)
}
func (m *AuthenticateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserResponse proto.InternalMessageInfo

func (m *AuthenticateUserResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *AuthenticateUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticateUserResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterCustomerRequest)(nil), "RegisterCustomerRequest")
	proto.RegisterType((*RegisterCustomerResponse)(nil), "RegisterCustomerResponse")
	proto.RegisterType((*IssueUserTokenRequest)(nil), "IssueUserTokenRequest")
	proto.RegisterType((*IssueUserTokenResponse)(nil), "IssueUserTokenResponse")
	proto.RegisterType((*AuthenticateUserRequest)(nil), "AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateUserResponse)(nil), "AuthenticateUserResponse")
}

func init() {
	proto.RegisterFile("user-management.proto", fileDescriptor_user_management_2f3ba80db759a4f0)
}

var fileDescriptor_user_management_2f3ba80db759a4f0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdd, 0x4a, 0xfb, 0x40,
	0x10, 0xc5, 0x9b, 0xfe, 0xdb, 0x3f, 0xed, 0x80, 0x45, 0x16, 0xdb, 0x6e, 0x83, 0x88, 0x04, 0x2f,
	0xbc, 0x71, 0x05, 0x7d, 0x02, 0x29, 0x0a, 0x81, 0x5a, 0x4a, 0xd4, 0x07, 0x58, 0xd3, 0xb1, 0x46,
	0x9b, 0x6c, 0xdd, 0xd9, 0xc5, 0x07, 0xf2, 0xf1, 0x7c, 0x09, 0xc9, 0x47, 0xdb, 0xf4, 0x23, 0x37,
	0x7a, 0x97, 0x39, 0xc3, 0xd9, 0xfc, 0xe6, 0xcc, 0x2e, 0x74, 0x2d, 0xa1, 0xbe, 0x88, 0x65, 0x22,
	0x67, 0x18, 0x63, 0x62, 0xc4, 0x42, 0x2b, 0xa3, 0xbc, 0x2f, 0x07, 0xfa, 0x01, 0xce, 0x22, 0x32,
	0xa8, 0x87, 0x96, 0x8c, 0x8a, 0x51, 0x07, 0xf8, 0x61, 0x91, 0x0c, 0x3b, 0x82, 0xe6, 0x6d, 0x2c,
	0xa3, 0x39, 0x77, 0x4e, 0x9d, 0xf3, 0x76, 0x90, 0x17, 0xcc, 0x85, 0xd6, 0x44, 0x12, 0x7d, 0x2a,
	0x3d, 0xe5, 0xf5, 0xac, 0xb1, 0xaa, 0xd9, 0x31, 0xb4, 0xef, 0x22, 0x4d, 0x66, 0x2c, 0x63, 0xe4,
	0xff, 0xb2, 0xe6, 0x5a, 0x48, 0x9d, 0x23, 0x59, 0x34, 0x1b, 0xb9, 0x73, 0x59, 0xa7, 0xce, 0x51,
	0x14, 0x62, 0x42, 0xe8, 0x4f, 0x79, 0x33, 0x77, 0xae, 0x04, 0x6f, 0x02, 0x7c, 0x17, 0x92, 0x16,
	0x2a, 0x21, 0x64, 0x27, 0x00, 0x0f, 0x36, 0x0c, 0x91, 0xe8, 0xc5, 0xe6, 0xa8, 0xad, 0xa0, 0xa4,
	0xa4, 0x53, 0x3c, 0xaa, 0x77, 0x4c, 0x0a, 0xd8, 0xbc, 0xf0, 0x7c, 0xe8, 0xfa, 0x44, 0x16, 0x9f,
	0x08, 0x75, 0xa6, 0xfc, 0x7a, 0x68, 0x6f, 0x0c, 0xbd, 0xed, 0xa3, 0xfe, 0x84, 0x76, 0x09, 0xfd,
	0x1b, 0x6b, 0x5e, 0x31, 0x31, 0x51, 0x28, 0x4d, 0x76, 0x6c, 0x09, 0x2e, 0x37, 0x38, 0x65, 0xc3,
	0x1b, 0xf0, 0x5d, 0x43, 0x81, 0x70, 0x06, 0x07, 0xe5, 0xde, 0xb4, 0xa0, 0xd8, 0x14, 0xd7, 0x43,
	0xd7, 0xcb, 0x43, 0x33, 0x68, 0x04, 0x6a, 0xbe, 0x5c, 0x64, 0xf6, 0x7d, 0xf5, 0xed, 0x40, 0x27,
	0xfd, 0xc1, 0xfd, 0xea, 0x22, 0x31, 0x1f, 0x0e, 0xb7, 0x97, 0xc3, 0xb8, 0xa8, 0xb8, 0x54, 0xee,
	0x40, 0x54, 0x6d, 0xd2, 0xab, 0xb1, 0x21, 0x74, 0x36, 0xa3, 0x64, 0x3d, 0xb1, 0x77, 0x4d, 0x6e,
	0x5f, 0xec, 0xcf, 0xdc, 0xab, 0xa5, 0x3c, 0xdb, 0x71, 0x30, 0x2e, 0x2a, 0x22, 0x75, 0x07, 0xa2,
	0x2a, 0x3b, 0xaf, 0xf6, 0xfc, 0x3f, 0x7b, 0x24, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02,
	0x81, 0x36, 0x56, 0x3d, 0x03, 0x00, 0x00,
}
