// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry.proto

package telemetry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_telemetry_372f0e2edf45aeec, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AllVehiclesResponse struct {
	Vehicles             []*AllVehiclesResponse_Vehicle `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *AllVehiclesResponse) Reset()         { *m = AllVehiclesResponse{} }
func (m *AllVehiclesResponse) String() string { return proto.CompactTextString(m) }
func (*AllVehiclesResponse) ProtoMessage()    {}
func (*AllVehiclesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_telemetry_372f0e2edf45aeec, []int{1}
}
func (m *AllVehiclesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllVehiclesResponse.Unmarshal(m, b)
}
func (m *AllVehiclesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllVehiclesResponse.Marshal(b, m, deterministic)
}
func (dst *AllVehiclesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllVehiclesResponse.Merge(dst, src)
}
func (m *AllVehiclesResponse) XXX_Size() int {
	return xxx_messageInfo_AllVehiclesResponse.Size(m)
}
func (m *AllVehiclesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllVehiclesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllVehiclesResponse proto.InternalMessageInfo

func (m *AllVehiclesResponse) GetVehicles() []*AllVehiclesResponse_Vehicle {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

type AllVehiclesResponse_Vehicle struct {
	VehicleId            string   `protobuf:"bytes,1,opt,name=VehicleId,proto3" json:"VehicleId,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	Battery              uint32   `protobuf:"varint,3,opt,name=Battery,proto3" json:"Battery,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllVehiclesResponse_Vehicle) Reset()         { *m = AllVehiclesResponse_Vehicle{} }
func (m *AllVehiclesResponse_Vehicle) String() string { return proto.CompactTextString(m) }
func (*AllVehiclesResponse_Vehicle) ProtoMessage()    {}
func (*AllVehiclesResponse_Vehicle) Descriptor() ([]byte, []int) {
	return fileDescriptor_telemetry_372f0e2edf45aeec, []int{1, 0}
}
func (m *AllVehiclesResponse_Vehicle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllVehiclesResponse_Vehicle.Unmarshal(m, b)
}
func (m *AllVehiclesResponse_Vehicle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllVehiclesResponse_Vehicle.Marshal(b, m, deterministic)
}
func (dst *AllVehiclesResponse_Vehicle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllVehiclesResponse_Vehicle.Merge(dst, src)
}
func (m *AllVehiclesResponse_Vehicle) XXX_Size() int {
	return xxx_messageInfo_AllVehiclesResponse_Vehicle.Size(m)
}
func (m *AllVehiclesResponse_Vehicle) XXX_DiscardUnknown() {
	xxx_messageInfo_AllVehiclesResponse_Vehicle.DiscardUnknown(m)
}

var xxx_messageInfo_AllVehiclesResponse_Vehicle proto.InternalMessageInfo

func (m *AllVehiclesResponse_Vehicle) GetVehicleId() string {
	if m != nil {
		return m.VehicleId
	}
	return ""
}

func (m *AllVehiclesResponse_Vehicle) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *AllVehiclesResponse_Vehicle) GetBattery() uint32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*AllVehiclesResponse)(nil), "AllVehiclesResponse")
	proto.RegisterType((*AllVehiclesResponse_Vehicle)(nil), "AllVehiclesResponse.Vehicle")
}

func init() { proto.RegisterFile("telemetry.proto", fileDescriptor_telemetry_372f0e2edf45aeec) }

var fileDescriptor_telemetry_372f0e2edf45aeec = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0xcd, 0x49,
	0xcd, 0x4d, 0x2d, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x62, 0xe7, 0x62, 0x75,
	0xcd, 0x2d, 0x28, 0xa9, 0x54, 0x5a, 0xc7, 0xc8, 0x25, 0xec, 0x98, 0x93, 0x13, 0x96, 0x9a, 0x91,
	0x99, 0x9c, 0x93, 0x5a, 0x1c, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xc1, 0xc5,
	0x51, 0x06, 0x15, 0x93, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd1, 0xc3, 0xa2, 0x4e, 0x0f,
	0x2a, 0x10, 0x04, 0x57, 0x2d, 0x15, 0xcb, 0xc5, 0x0e, 0x15, 0x14, 0x92, 0xe1, 0xe2, 0x84, 0x32,
	0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x52, 0x5c, 0x1c, 0x3e,
	0xf9, 0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x60, 0x49, 0x38, 0x5f, 0x48, 0x82, 0x8b,
	0xdd, 0x29, 0xb1, 0xa4, 0x24, 0xb5, 0xa8, 0x52, 0x82, 0x59, 0x81, 0x51, 0x83, 0x37, 0x08, 0xc6,
	0x35, 0xb2, 0xe2, 0xe2, 0x0c, 0x81, 0x79, 0x46, 0x48, 0x97, 0x8b, 0x1b, 0xc9, 0x51, 0x42, 0x6c,
	0x7a, 0x60, 0x4f, 0x49, 0x89, 0x60, 0x73, 0xaa, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0xf3, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x42, 0xf7, 0xf2, 0x0f, 0x01, 0x00, 0x00,
}
