// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fleet-controller.proto

package fleet_controller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type BookingRequest struct {
	VehicleId            string   `protobuf:"bytes,1,opt,name=VehicleId,proto3" json:"VehicleId,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingRequest) Reset()         { *m = BookingRequest{} }
func (m *BookingRequest) String() string { return proto.CompactTextString(m) }
func (*BookingRequest) ProtoMessage()    {}
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{1}
}
func (m *BookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingRequest.Unmarshal(m, b)
}
func (m *BookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingRequest.Marshal(b, m, deterministic)
}
func (dst *BookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingRequest.Merge(dst, src)
}
func (m *BookingRequest) XXX_Size() int {
	return xxx_messageInfo_BookingRequest.Size(m)
}
func (m *BookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingRequest proto.InternalMessageInfo

func (m *BookingRequest) GetVehicleId() string {
	if m != nil {
		return m.VehicleId
	}
	return ""
}

func (m *BookingRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type BookingResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	ReservedTime         uint32   `protobuf:"varint,2,opt,name=ReservedTime,proto3" json:"ReservedTime,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingResponse) Reset()         { *m = BookingResponse{} }
func (m *BookingResponse) String() string { return proto.CompactTextString(m) }
func (*BookingResponse) ProtoMessage()    {}
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{2}
}
func (m *BookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingResponse.Unmarshal(m, b)
}
func (m *BookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingResponse.Marshal(b, m, deterministic)
}
func (dst *BookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingResponse.Merge(dst, src)
}
func (m *BookingResponse) XXX_Size() int {
	return xxx_messageInfo_BookingResponse.Size(m)
}
func (m *BookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingResponse proto.InternalMessageInfo

func (m *BookingResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *BookingResponse) GetReservedTime() uint32 {
	if m != nil {
		return m.ReservedTime
	}
	return 0
}

func (m *BookingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UnbookingRequest struct {
	VehicleId            string   `protobuf:"bytes,1,opt,name=VehicleId,proto3" json:"VehicleId,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbookingRequest) Reset()         { *m = UnbookingRequest{} }
func (m *UnbookingRequest) String() string { return proto.CompactTextString(m) }
func (*UnbookingRequest) ProtoMessage()    {}
func (*UnbookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{3}
}
func (m *UnbookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbookingRequest.Unmarshal(m, b)
}
func (m *UnbookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbookingRequest.Marshal(b, m, deterministic)
}
func (dst *UnbookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbookingRequest.Merge(dst, src)
}
func (m *UnbookingRequest) XXX_Size() int {
	return xxx_messageInfo_UnbookingRequest.Size(m)
}
func (m *UnbookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbookingRequest proto.InternalMessageInfo

func (m *UnbookingRequest) GetVehicleId() string {
	if m != nil {
		return m.VehicleId
	}
	return ""
}

func (m *UnbookingRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type UnbookingResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbookingResponse) Reset()         { *m = UnbookingResponse{} }
func (m *UnbookingResponse) String() string { return proto.CompactTextString(m) }
func (*UnbookingResponse) ProtoMessage()    {}
func (*UnbookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{4}
}
func (m *UnbookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbookingResponse.Unmarshal(m, b)
}
func (m *UnbookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbookingResponse.Marshal(b, m, deterministic)
}
func (dst *UnbookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbookingResponse.Merge(dst, src)
}
func (m *UnbookingResponse) XXX_Size() int {
	return xxx_messageInfo_UnbookingResponse.Size(m)
}
func (m *UnbookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnbookingResponse proto.InternalMessageInfo

func (m *UnbookingResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *UnbookingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BeginRideRequest struct {
	CustomerId           string   `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginRideRequest) Reset()         { *m = BeginRideRequest{} }
func (m *BeginRideRequest) String() string { return proto.CompactTextString(m) }
func (*BeginRideRequest) ProtoMessage()    {}
func (*BeginRideRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{5}
}
func (m *BeginRideRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginRideRequest.Unmarshal(m, b)
}
func (m *BeginRideRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginRideRequest.Marshal(b, m, deterministic)
}
func (dst *BeginRideRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginRideRequest.Merge(dst, src)
}
func (m *BeginRideRequest) XXX_Size() int {
	return xxx_messageInfo_BeginRideRequest.Size(m)
}
func (m *BeginRideRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginRideRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginRideRequest proto.InternalMessageInfo

func (m *BeginRideRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type BeginRideResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginRideResponse) Reset()         { *m = BeginRideResponse{} }
func (m *BeginRideResponse) String() string { return proto.CompactTextString(m) }
func (*BeginRideResponse) ProtoMessage()    {}
func (*BeginRideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{6}
}
func (m *BeginRideResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginRideResponse.Unmarshal(m, b)
}
func (m *BeginRideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginRideResponse.Marshal(b, m, deterministic)
}
func (dst *BeginRideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginRideResponse.Merge(dst, src)
}
func (m *BeginRideResponse) XXX_Size() int {
	return xxx_messageInfo_BeginRideResponse.Size(m)
}
func (m *BeginRideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginRideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeginRideResponse proto.InternalMessageInfo

func (m *BeginRideResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *BeginRideResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EndRideRequest struct {
	CustomerId           string   `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndRideRequest) Reset()         { *m = EndRideRequest{} }
func (m *EndRideRequest) String() string { return proto.CompactTextString(m) }
func (*EndRideRequest) ProtoMessage()    {}
func (*EndRideRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{7}
}
func (m *EndRideRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndRideRequest.Unmarshal(m, b)
}
func (m *EndRideRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndRideRequest.Marshal(b, m, deterministic)
}
func (dst *EndRideRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndRideRequest.Merge(dst, src)
}
func (m *EndRideRequest) XXX_Size() int {
	return xxx_messageInfo_EndRideRequest.Size(m)
}
func (m *EndRideRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndRideRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndRideRequest proto.InternalMessageInfo

func (m *EndRideRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type EndRideResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndRideResponse) Reset()         { *m = EndRideResponse{} }
func (m *EndRideResponse) String() string { return proto.CompactTextString(m) }
func (*EndRideResponse) ProtoMessage()    {}
func (*EndRideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{8}
}
func (m *EndRideResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndRideResponse.Unmarshal(m, b)
}
func (m *EndRideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndRideResponse.Marshal(b, m, deterministic)
}
func (dst *EndRideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndRideResponse.Merge(dst, src)
}
func (m *EndRideResponse) XXX_Size() int {
	return xxx_messageInfo_EndRideResponse.Size(m)
}
func (m *EndRideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndRideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndRideResponse proto.InternalMessageInfo

func (m *EndRideResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *EndRideResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RetrieveReservationsResponse struct {
	Reservations         []*RetrieveReservationsResponse_Reservation `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	Error                string                                      `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *RetrieveReservationsResponse) Reset()         { *m = RetrieveReservationsResponse{} }
func (m *RetrieveReservationsResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveReservationsResponse) ProtoMessage()    {}
func (*RetrieveReservationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{9}
}
func (m *RetrieveReservationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveReservationsResponse.Unmarshal(m, b)
}
func (m *RetrieveReservationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveReservationsResponse.Marshal(b, m, deterministic)
}
func (dst *RetrieveReservationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveReservationsResponse.Merge(dst, src)
}
func (m *RetrieveReservationsResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveReservationsResponse.Size(m)
}
func (m *RetrieveReservationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveReservationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveReservationsResponse proto.InternalMessageInfo

func (m *RetrieveReservationsResponse) GetReservations() []*RetrieveReservationsResponse_Reservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

func (m *RetrieveReservationsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RetrieveReservationsResponse_Reservation struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Vehicle              string   `protobuf:"bytes,3,opt,name=Vehicle,proto3" json:"Vehicle,omitempty"`
	Customer             string   `protobuf:"bytes,4,opt,name=Customer,proto3" json:"Customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveReservationsResponse_Reservation) Reset() {
	*m = RetrieveReservationsResponse_Reservation{}
}
func (m *RetrieveReservationsResponse_Reservation) String() string { return proto.CompactTextString(m) }
func (*RetrieveReservationsResponse_Reservation) ProtoMessage()    {}
func (*RetrieveReservationsResponse_Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_fleet_controller_eadb88a0c74ad55c, []int{9, 0}
}
func (m *RetrieveReservationsResponse_Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveReservationsResponse_Reservation.Unmarshal(m, b)
}
func (m *RetrieveReservationsResponse_Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveReservationsResponse_Reservation.Marshal(b, m, deterministic)
}
func (dst *RetrieveReservationsResponse_Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveReservationsResponse_Reservation.Merge(dst, src)
}
func (m *RetrieveReservationsResponse_Reservation) XXX_Size() int {
	return xxx_messageInfo_RetrieveReservationsResponse_Reservation.Size(m)
}
func (m *RetrieveReservationsResponse_Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveReservationsResponse_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveReservationsResponse_Reservation proto.InternalMessageInfo

func (m *RetrieveReservationsResponse_Reservation) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RetrieveReservationsResponse_Reservation) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RetrieveReservationsResponse_Reservation) GetVehicle() string {
	if m != nil {
		return m.Vehicle
	}
	return ""
}

func (m *RetrieveReservationsResponse_Reservation) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*BookingRequest)(nil), "BookingRequest")
	proto.RegisterType((*BookingResponse)(nil), "BookingResponse")
	proto.RegisterType((*UnbookingRequest)(nil), "UnbookingRequest")
	proto.RegisterType((*UnbookingResponse)(nil), "UnbookingResponse")
	proto.RegisterType((*BeginRideRequest)(nil), "BeginRideRequest")
	proto.RegisterType((*BeginRideResponse)(nil), "BeginRideResponse")
	proto.RegisterType((*EndRideRequest)(nil), "EndRideRequest")
	proto.RegisterType((*EndRideResponse)(nil), "EndRideResponse")
	proto.RegisterType((*RetrieveReservationsResponse)(nil), "RetrieveReservationsResponse")
	proto.RegisterType((*RetrieveReservationsResponse_Reservation)(nil), "RetrieveReservationsResponse.Reservation")
}

func init() {
	proto.RegisterFile("fleet-controller.proto", fileDescriptor_fleet_controller_eadb88a0c74ad55c)
}

var fileDescriptor_fleet_controller_eadb88a0c74ad55c = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x1d, 0xa7, 0x4d, 0x9a, 0x69, 0x1b, 0x27, 0xa3, 0x0a, 0x59, 0x56, 0x41, 0xd5, 0x9e,
	0x8a, 0x10, 0x2b, 0x08, 0xdc, 0x11, 0x8d, 0x02, 0xf2, 0x01, 0x84, 0x96, 0x3f, 0xf7, 0xd6, 0x9e,
	0x16, 0xab, 0x8e, 0x37, 0xdd, 0x5d, 0x57, 0xe2, 0x9b, 0xf0, 0x49, 0x39, 0x23, 0x6f, 0x1c, 0x77,
	0xed, 0x56, 0x55, 0x51, 0x39, 0xee, 0x5b, 0xbd, 0x99, 0xb1, 0xe7, 0xf7, 0x16, 0x9e, 0x9c, 0xe7,
	0x44, 0xe6, 0x65, 0x22, 0x0b, 0xa3, 0x64, 0x9e, 0x93, 0xe2, 0x2b, 0x25, 0x8d, 0x64, 0x43, 0xd8,
	0x5e, 0x2c, 0x57, 0xe6, 0x17, 0xfb, 0x0c, 0xe3, 0x13, 0x29, 0x2f, 0xb3, 0xe2, 0x42, 0xd0, 0x55,
	0x49, 0xda, 0xe0, 0x21, 0x8c, 0x7e, 0xd0, 0xcf, 0x2c, 0xc9, 0x29, 0x4e, 0xc3, 0xde, 0x51, 0xef,
	0x78, 0x24, 0x6e, 0x04, 0x7c, 0x06, 0x30, 0x2f, 0xb5, 0x91, 0x4b, 0x52, 0x71, 0x1a, 0xfa, 0xf6,
	0xda, 0x51, 0xd8, 0x25, 0x04, 0x4d, 0x3d, 0xbd, 0x92, 0x85, 0xa6, 0xca, 0xf2, 0xb5, 0x4c, 0x12,
	0xd2, 0xfa, 0xbc, 0xcc, 0x6d, 0xc5, 0x1d, 0xe1, 0x28, 0xc8, 0x60, 0x4f, 0x90, 0x26, 0x75, 0x4d,
	0xe9, 0xb7, 0x6c, 0x49, 0xb6, 0xe8, 0xbe, 0x68, 0x69, 0x78, 0x00, 0xdb, 0x0b, 0xa5, 0xa4, 0x0a,
	0xfb, 0xb6, 0xe3, 0xfa, 0xc0, 0xbe, 0xc0, 0xe4, 0x7b, 0x71, 0xf6, 0x3f, 0xc7, 0x8f, 0x61, 0xea,
	0x54, 0x7c, 0xe0, 0x07, 0x34, 0xc3, 0xf9, 0xee, 0x70, 0x33, 0x98, 0x9c, 0xd0, 0x45, 0x56, 0x88,
	0x2c, 0xa5, 0xcd, 0x70, 0x0f, 0x68, 0xef, 0x78, 0x1e, 0xd5, 0xfe, 0x15, 0x8c, 0x17, 0x45, 0xfa,
	0x2f, 0xcd, 0x3f, 0x42, 0xd0, 0x38, 0x1e, 0xd5, 0xfa, 0x4f, 0x0f, 0x0e, 0x05, 0x19, 0x95, 0xd1,
	0x35, 0xad, 0xb7, 0x78, 0x6a, 0x32, 0x59, 0xe8, 0xa6, 0xec, 0x27, 0xd8, 0x53, 0x8e, 0x1e, 0xf6,
	0x8e, 0xfa, 0xc7, 0xbb, 0xb3, 0xe7, 0xfc, 0x3e, 0x13, 0x77, 0x44, 0xd1, 0xb2, 0xdf, 0x3d, 0x45,
	0x74, 0x05, 0xbb, 0x8e, 0x05, 0xc7, 0xe0, 0xd7, 0x40, 0xec, 0x0b, 0x3f, 0x4e, 0x2b, 0x4e, 0xe6,
	0x8a, 0x4e, 0x0d, 0xa5, 0xef, 0x8d, 0x35, 0xf6, 0xc5, 0x8d, 0x80, 0x21, 0x0c, 0x6b, 0x68, 0x6a,
	0xe2, 0x36, 0x47, 0x8c, 0x60, 0x67, 0xf3, 0xcf, 0xc2, 0x2d, 0x7b, 0xd5, 0x9c, 0x67, 0xbf, 0x7d,
	0x08, 0x3e, 0x54, 0x81, 0x9b, 0x37, 0x79, 0xc3, 0x17, 0xb0, 0x55, 0x05, 0x02, 0x03, 0xde, 0xce,
	0x59, 0x34, 0xe1, 0x9d, 0xa0, 0x30, 0x0f, 0x5f, 0xc3, 0x60, 0x8d, 0x1f, 0x4e, 0x79, 0x97, 0xec,
	0x08, 0xf9, 0x2d, 0x34, 0x99, 0x87, 0x6f, 0x61, 0xd4, 0x20, 0x83, 0x53, 0xde, 0x45, 0x2e, 0x42,
	0x7e, 0x8b, 0x28, 0xe6, 0x21, 0x87, 0x61, 0xbd, 0x6b, 0x0c, 0x78, 0x9b, 0x93, 0x68, 0xc2, 0x3b,
	0x18, 0x30, 0x0f, 0xdf, 0xc1, 0xc1, 0x5d, 0xcb, 0xc1, 0x01, 0xb7, 0xcf, 0x48, 0xf4, 0xf4, 0xde,
	0xdd, 0x31, 0xef, 0x6c, 0x60, 0xdf, 0x9d, 0x37, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xd2,
	0x29, 0x31, 0x91, 0x04, 0x00, 0x00,
}
