// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statistics.proto

package statistics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RetrieveBookingsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveBookingsRequest) Reset()         { *m = RetrieveBookingsRequest{} }
func (m *RetrieveBookingsRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveBookingsRequest) ProtoMessage()    {}
func (*RetrieveBookingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_statistics_11bdbe2688980a6c, []int{0}
}
func (m *RetrieveBookingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBookingsRequest.Unmarshal(m, b)
}
func (m *RetrieveBookingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBookingsRequest.Marshal(b, m, deterministic)
}
func (dst *RetrieveBookingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBookingsRequest.Merge(dst, src)
}
func (m *RetrieveBookingsRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveBookingsRequest.Size(m)
}
func (m *RetrieveBookingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBookingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBookingsRequest proto.InternalMessageInfo

func (m *RetrieveBookingsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RetrieveBookingsResponse struct {
	Bookings             []*RetrieveBookingsResponse_Booking `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *RetrieveBookingsResponse) Reset()         { *m = RetrieveBookingsResponse{} }
func (m *RetrieveBookingsResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveBookingsResponse) ProtoMessage()    {}
func (*RetrieveBookingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_statistics_11bdbe2688980a6c, []int{1}
}
func (m *RetrieveBookingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBookingsResponse.Unmarshal(m, b)
}
func (m *RetrieveBookingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBookingsResponse.Marshal(b, m, deterministic)
}
func (dst *RetrieveBookingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBookingsResponse.Merge(dst, src)
}
func (m *RetrieveBookingsResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveBookingsResponse.Size(m)
}
func (m *RetrieveBookingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBookingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBookingsResponse proto.InternalMessageInfo

func (m *RetrieveBookingsResponse) GetBookings() []*RetrieveBookingsResponse_Booking {
	if m != nil {
		return m.Bookings
	}
	return nil
}

type RetrieveBookingsResponse_Booking struct {
	CreatedAt            int64    `protobuf:"varint,1,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	VehicleId            string   `protobuf:"bytes,2,opt,name=VehicleId,proto3" json:"VehicleId,omitempty"`
	AmountPaid           float32  `protobuf:"fixed32,3,opt,name=AmountPaid,proto3" json:"AmountPaid,omitempty"`
	DistanceDriven       uint32   `protobuf:"varint,4,opt,name=DistanceDriven,proto3" json:"DistanceDriven,omitempty"`
	TimeDriven           uint32   `protobuf:"varint,5,opt,name=TimeDriven,proto3" json:"TimeDriven,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveBookingsResponse_Booking) Reset()         { *m = RetrieveBookingsResponse_Booking{} }
func (m *RetrieveBookingsResponse_Booking) String() string { return proto.CompactTextString(m) }
func (*RetrieveBookingsResponse_Booking) ProtoMessage()    {}
func (*RetrieveBookingsResponse_Booking) Descriptor() ([]byte, []int) {
	return fileDescriptor_statistics_11bdbe2688980a6c, []int{1, 0}
}
func (m *RetrieveBookingsResponse_Booking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBookingsResponse_Booking.Unmarshal(m, b)
}
func (m *RetrieveBookingsResponse_Booking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBookingsResponse_Booking.Marshal(b, m, deterministic)
}
func (dst *RetrieveBookingsResponse_Booking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBookingsResponse_Booking.Merge(dst, src)
}
func (m *RetrieveBookingsResponse_Booking) XXX_Size() int {
	return xxx_messageInfo_RetrieveBookingsResponse_Booking.Size(m)
}
func (m *RetrieveBookingsResponse_Booking) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBookingsResponse_Booking.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBookingsResponse_Booking proto.InternalMessageInfo

func (m *RetrieveBookingsResponse_Booking) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RetrieveBookingsResponse_Booking) GetVehicleId() string {
	if m != nil {
		return m.VehicleId
	}
	return ""
}

func (m *RetrieveBookingsResponse_Booking) GetAmountPaid() float32 {
	if m != nil {
		return m.AmountPaid
	}
	return 0
}

func (m *RetrieveBookingsResponse_Booking) GetDistanceDriven() uint32 {
	if m != nil {
		return m.DistanceDriven
	}
	return 0
}

func (m *RetrieveBookingsResponse_Booking) GetTimeDriven() uint32 {
	if m != nil {
		return m.TimeDriven
	}
	return 0
}

func init() {
	proto.RegisterType((*RetrieveBookingsRequest)(nil), "RetrieveBookingsRequest")
	proto.RegisterType((*RetrieveBookingsResponse)(nil), "RetrieveBookingsResponse")
	proto.RegisterType((*RetrieveBookingsResponse_Booking)(nil), "RetrieveBookingsResponse.Booking")
}

func init() { proto.RegisterFile("statistics.proto", fileDescriptor_statistics_11bdbe2688980a6c) }

var fileDescriptor_statistics_11bdbe2688980a6c = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x5d, 0xaa, 0x28, 0x63, 0x34, 0x64, 0x0f, 0xba, 0x12, 0x63, 0x6a, 0x0f, 0xa6, 0xa7,
	0x26, 0xe2, 0xd9, 0x03, 0xca, 0xa5, 0x37, 0xb3, 0xfe, 0x3b, 0x97, 0x76, 0xa2, 0x13, 0x65, 0x17,
	0x77, 0x06, 0xbe, 0x83, 0x1f, 0xc6, 0xef, 0x68, 0x68, 0x2a, 0x10, 0x4c, 0x8f, 0xfb, 0xdb, 0xf7,
	0x26, 0x6f, 0xde, 0x40, 0x9f, 0xa5, 0x10, 0x62, 0xa1, 0x92, 0xb3, 0x59, 0xf0, 0xe2, 0x93, 0x6b,
	0x38, 0xb5, 0x28, 0x81, 0x70, 0x81, 0x77, 0xde, 0x7f, 0x90, 0x7b, 0x63, 0x8b, 0x5f, 0x73, 0x64,
	0xd1, 0x27, 0xd0, 0x7d, 0x66, 0x0c, 0x79, 0x65, 0x54, 0xac, 0xd2, 0x9e, 0x6d, 0x5e, 0xc9, 0x77,
	0x07, 0xcc, 0x7f, 0x0f, 0xcf, 0xbc, 0x63, 0xd4, 0xb7, 0x70, 0x30, 0x69, 0x98, 0x51, 0x71, 0x94,
	0x1e, 0x0e, 0x2f, 0xb3, 0x36, 0x71, 0xd6, 0x00, 0xbb, 0xb2, 0x0c, 0x7e, 0x14, 0xec, 0x37, 0x54,
	0x9f, 0x43, 0xef, 0x3e, 0x60, 0x21, 0x58, 0x8d, 0xa4, 0x8e, 0x10, 0xd9, 0x35, 0x58, 0xfe, 0xbe,
	0xe0, 0x3b, 0x95, 0x9f, 0x98, 0x57, 0xa6, 0x53, 0x07, 0x5c, 0x03, 0x7d, 0x01, 0x30, 0x9a, 0xfa,
	0xb9, 0x93, 0x87, 0x82, 0x2a, 0x13, 0xc5, 0x2a, 0xed, 0xd8, 0x0d, 0xa2, 0xaf, 0xe0, 0x78, 0x4c,
	0x2c, 0x85, 0x2b, 0x71, 0x1c, 0x68, 0x81, 0xce, 0xec, 0xc6, 0x2a, 0x3d, 0xb2, 0x5b, 0x74, 0x39,
	0xe7, 0x89, 0xa6, 0x7f, 0x9a, 0xbd, 0x5a, 0xb3, 0x41, 0x86, 0xaf, 0x00, 0x8f, 0xab, 0x4a, 0x75,
	0x0e, 0xfd, 0xed, 0x5d, 0xb5, 0xc9, 0x5a, 0xfa, 0x1d, 0x9c, 0xb5, 0x16, 0x93, 0xec, 0x4c, 0xba,
	0xf5, 0x79, 0x6e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x82, 0x52, 0xe7, 0xb2, 0x01, 0x00,
	0x00,
}
