// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: statistics.proto

/*
Package statistics is a generated protocol buffer package.

It is generated from these files:
	statistics.proto

It has these top-level messages:
	RetrieveBookingsRequest
	RetrieveBookingsResponse
*/
package statistics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Statistics service

type StatisticsService interface {
	RetrieveBookings(ctx context.Context, in *RetrieveBookingsRequest, opts ...client.CallOption) (*RetrieveBookingsResponse, error)
}

type statisticsService struct {
	c    client.Client
	name string
}

func NewStatisticsService(name string, c client.Client) StatisticsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "statistics"
	}
	return &statisticsService{
		c:    c,
		name: name,
	}
}

func (c *statisticsService) RetrieveBookings(ctx context.Context, in *RetrieveBookingsRequest, opts ...client.CallOption) (*RetrieveBookingsResponse, error) {
	req := c.c.NewRequest(c.name, "Statistics.RetrieveBookings", in)
	out := new(RetrieveBookingsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Statistics service

type StatisticsHandler interface {
	RetrieveBookings(context.Context, *RetrieveBookingsRequest, *RetrieveBookingsResponse) error
}

func RegisterStatisticsHandler(s server.Server, hdlr StatisticsHandler, opts ...server.HandlerOption) {
	type statistics interface {
		RetrieveBookings(ctx context.Context, in *RetrieveBookingsRequest, out *RetrieveBookingsResponse) error
	}
	type Statistics struct {
		statistics
	}
	h := &statisticsHandler{hdlr}
	s.Handle(s.NewHandler(&Statistics{h}, opts...))
}

type statisticsHandler struct {
	StatisticsHandler
}

func (h *statisticsHandler) RetrieveBookings(ctx context.Context, in *RetrieveBookingsRequest, out *RetrieveBookingsResponse) error {
	return h.StatisticsHandler.RetrieveBookings(ctx, in, out)
}
